name: Basic Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      - name: Lint
        run: |
          yarn lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      - name: Typecheck
        run: |
          yarn typecheck

  prepare-test:
    name: Prepare Test
    runs-on: ubuntu-latest
    outputs:
      workspace-paths: ${{ steps.list-workspaces.outputs.workspace-paths }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          skip-yarn-install: true
      - name: List workspaces with tests
        uses: zetavg/yarn-workspaces-list-action@v2.pre1
        id: list-workspaces
        with:
          # Check if the workspace has a "test" script defined in its package.json.
          condition: '[ -f "$workspace_path/package.json" ] && jq -e ".scripts.test" "$workspace_path/package.json"'

  test:
    name: Test ${{ matrix.dir }}
    needs: prepare-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.prepare-test.outputs.workspace-paths) }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      - name: Test
        run: |
          yarn test
